apiVersion: samples.knative.dev/v1alpha1
kind: BrokerChannel
metadata:
  name: test-motion
  namespace: default
spec:
  brokeraddr: 10.244.1.61 # Set the IP address of the mosquitto Pod
  brokerport: 1883
  topic: motion
  sink:
    ref: # Change the apiVersion and kind accordingly
      apiVersion: v1
      kind: Service
      name: helloworld-go