apiVersion: samples.knative.dev/v1alpha1
kind: BrokerChannel
metadata:
  name: test
  namespace: default
spec:
  brokeraddr: 10.244.1.220 
  brokerport: 1883
  topic: motion
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1 #messaging.knative.dev/v1
      kind: InMemoryChannel
      name: camel-test
