/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cowbon/brokerchannel/pkg/apis/samples/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBrokerChannels implements BrokerChannelInterface
type FakeBrokerChannels struct {
	Fake *FakeSamplesV1alpha1
	ns   string
}

var brokerchannelsResource = schema.GroupVersionResource{Group: "samples.knative.dev", Version: "v1alpha1", Resource: "brokerchannels"}

var brokerchannelsKind = schema.GroupVersionKind{Group: "samples.knative.dev", Version: "v1alpha1", Kind: "BrokerChannel"}

// Get takes name of the brokerChannel, and returns the corresponding brokerChannel object, and an error if there is any.
func (c *FakeBrokerChannels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BrokerChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(brokerchannelsResource, c.ns, name), &v1alpha1.BrokerChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerChannel), err
}

// List takes label and field selectors, and returns the list of BrokerChannels that match those selectors.
func (c *FakeBrokerChannels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BrokerChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(brokerchannelsResource, brokerchannelsKind, c.ns, opts), &v1alpha1.BrokerChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BrokerChannelList{ListMeta: obj.(*v1alpha1.BrokerChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.BrokerChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested brokerChannels.
func (c *FakeBrokerChannels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(brokerchannelsResource, c.ns, opts))

}

// Create takes the representation of a brokerChannel and creates it.  Returns the server's representation of the brokerChannel, and an error, if there is any.
func (c *FakeBrokerChannels) Create(ctx context.Context, brokerChannel *v1alpha1.BrokerChannel, opts v1.CreateOptions) (result *v1alpha1.BrokerChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(brokerchannelsResource, c.ns, brokerChannel), &v1alpha1.BrokerChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerChannel), err
}

// Update takes the representation of a brokerChannel and updates it. Returns the server's representation of the brokerChannel, and an error, if there is any.
func (c *FakeBrokerChannels) Update(ctx context.Context, brokerChannel *v1alpha1.BrokerChannel, opts v1.UpdateOptions) (result *v1alpha1.BrokerChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(brokerchannelsResource, c.ns, brokerChannel), &v1alpha1.BrokerChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBrokerChannels) UpdateStatus(ctx context.Context, brokerChannel *v1alpha1.BrokerChannel, opts v1.UpdateOptions) (*v1alpha1.BrokerChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(brokerchannelsResource, "status", c.ns, brokerChannel), &v1alpha1.BrokerChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerChannel), err
}

// Delete takes name of the brokerChannel and deletes it. Returns an error if one occurs.
func (c *FakeBrokerChannels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(brokerchannelsResource, c.ns, name), &v1alpha1.BrokerChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBrokerChannels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(brokerchannelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BrokerChannelList{})
	return err
}

// Patch applies the patch and returns the patched brokerChannel.
func (c *FakeBrokerChannels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BrokerChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(brokerchannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BrokerChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BrokerChannel), err
}
